### ISSUE TITLE
Decide on Technical Structure/Architecture

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/linked-data-repository#3]
Take a look at the historical [rcubed project](https://github.com/GSS-Cogs/rcubed) which might contain some useful ideas.

How are we going to host the linked data repository?

- Shall we host it inside kubernetes to take advantage of our existing backup-and-restore functionality?
- Should it run on lambdas
  - If running inside k8s we could still use serverless functions like [openFaaS](https://www.openfaas.com/) (see [here](https://medium.com/appvia/serverless-on-kubernetes-63b49aeaf4ef) for more)
- Or do we need some kind of message queueing system to process upload requests?
- Do we store our CSV-Ws on a bucket or github or somewhere else?
- Which language do we use to develop this in?
  - Which frameworks do we use for things like HTTP request handling, etc?
- How do we develop the 'front-end'?
  - Single page app?
  - Individual HTML pages with vanilla Javascript making some basic fetch API GET requests?
- Do we need a staging environment & production environment?
- What sort of database will we use to catalogue which versions are available and where the relevant files are stored?
- Should we implement some kind of basic HTTP response caching to quickly serve up common requests?
  - How would this cope if it tries to cache a 2GB file?
- Should we make sure the API responds with an [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)/[Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) header to improve client-side caching?
- Do we want to use swagger or OpenAPI to document the end-points?
- How do we cope with authentication of uploaders?

**Comment by mikeAdamss** [comment]
good questions, expect many ramblings :)

The GCP implementations of lambdas/serverless are:
- Cloud Function: (ancient example: https://github.com/mikeAdamss/cloudfunc-file-mover)
- Cloud Run (Container as a service, Caas), same deal but you build and push a docker image rather than just function code.

For something like a http get endpoints I'd trend towards the former. If all we're doing is returning a signed url to a bucket or some json it'll be very light weight (regardless of other decisions, things like dumps of RDF will end up in buckets).

I don't think a kubernetes cluster would be necessary for the gets, serverless horizontally scales by default, if its just simple request response ("here, have a one use signed url for a downloadable thing") the default behaviour is more than ample.

Same on language, if you want an uber fast and concurrent api service you'd probably write it in golang but thats a bit like killing ants with a rocket launcher for this. I'd just keep in simple, once you have a url signing function (I have one somewhere) a python cloud function to, i.e "get me a signed url to download x" or "get me x json" will be very light weight.

Assuming we did go with python and serverless its Flask (more or less, possibly a variant), that's the framework that powers cloud functions I believe.

The meatier things (generating RDF, resumable uploads) might need a different approach, but getting stuff out should be simple enough.

**Comment by mikeAdamss** [comment]
its a bit hand wavey but initial sketch on concept, trying to keep the implementation details out but its tricky: https://drive.google.com/file/d/1-udxklEBd-HXY8OPTeshgg4cqNn5K5lb/view?usp=sharing

**Comment by mikeAdamss** [comment]
**How do we cope with authentication of uploaders?**

If the uploaders are just us I'd lean towards to just use the GCP IAM system, i.e to trigger a cloud function you need the `Cloud Function Invoke` permission for it. Our team would/should have their own credentials, Jenkins/other services would need a service account.

If you're aiming wide than us we're into user databases and fun with JIT tokens and/or Oauth.

**Comment by mikeAdamss** [comment]
**Serverless vs not serverless**

I'm increasingly convinced it's both (bear with), the advantages of horizontal scaling only really apply in the **public** facing parts of this, which is a good use case for serverless, as the end points will be super light touch (principally just going to serving up resources that were computed and held elsewhere).

The **private** parts  (the upload process) differ in that they  (a) need more computational resource and (b) don't need that level of horizontal scaling as there's a much smaller user base that could be triggering them. So that's more the use case for some meatier services held together with some message queues to handle excessive concurrent builds.

public - serverless
private - real servers with queues

@robons - how does that thought sit with you?

**Comment by robons** [comment]
> **Serverless vs not serverless**
> 
> I'm increasingly convinced it's both (bear with), the advantages of horizontal scaling only really apply in the **public** facing parts of this, which is a good use case for serverless, as the end points will be super light touch (principally just going to serving up resources that were computed and held elsewhere).
> 
> The **private** parts (the upload process) differ in that they (a) need more computational resource and (b) don't need that level of horizontal scaling as there's a much smaller user base that could be triggering them. So that's more the use case for some meatier services held together with some message queues to handle excessive concurrent builds.
> 
> public - serverless private - real servers with queues
> 
> @robons - how does that thought sit with you?

My thoughts are that serverless is great for things like IOT sensors where start-up times for endpoints don't matter. Users aren't going to notice if their internet connected washing machine takes a few seconds longer to log some status to the server. And I think they *can* be useful for asynchronous processing of small amounts of data where you queue some stuff up and trigger a function which retrieves something from a bucket, does some transformation and sticks it back in to another bucket. However, there are two things that serverless functions do that I'm not thrilled about: 

* Long start-up times on user-facing APIs.
* Automatic timeouts where processes take too long.

On long start-up times, I know that you can do things like keep lambdas warm - but what's the benefit here over a well-scaled 'real server'?

On automatic timeouts - sure you can extend the timeout, but then you're a resource hog without any queueing mechanism to moderate demand.

I guess I just don't get what the benefit of serverless functions are when serving up a user-facing API where milliseconds to response are important. This isn't to say I'm necessarily against using them, but I'm not entirely convinced of their utility for our purposes.

On your suggestion of message queues and long-running processes. I'm all for those. As long as we can scale-up the long-running processes and distibute messages across them, I think we end up in a good flexible position where we get good response times even when our service isn't being heavily utilised (and we only have one instance).

**Comment by mikeAdamss** [comment]
I just like having all the scaling hands free and there's a lot of clarity in microservices (one endpoint = one function), makes for nice maintainable things.

but honestly, the public backend of this is gonna be like 4 endpoints, so I'm not opposed to keeping it simple - happy to just have a single server for them.
